services:
  fastapi:
    build: fastapi-backend
    container_name: fastapi-most
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - most-network

networks:
  most-network:
    driver: bridge
