[project]
name = "fastapi-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "fastexcel>=0.14.0",
    "polars>=1.33.0",
    "uvicorn>=0.35.0",
]
